---
"extends": "xo-space"
"env":
  "mocha": true
  "amd": true
  "browser": true
"rules":
  "comma-dangle":
    - 2
    - "always-multiline"
  "object-curly-spacing":
    - 2
    - "always"
  "linebreak-style": 0
  "no-warning-comments": 0
