define({
  title: 'Northwind Schema',
  type: 'object',
  properties: {
    CustomerID: {
      type: 'string',
      filterable: true,
      nullable: false,
      required: true,
      aggregateType: 'count',
    },
    EmployeeID: {
      type: 'number',
      filterable: true,
      nullable: false,
      required: true,
      aggregateType: 'count',
    },
    ShipName: {
      type: 'string',
      filterable: true,
      nullable: false,
      required: true,
      aggregateType: 'count',
    },
    OrderID: {
      type: 'integer',
    },
    Freight: {
      type: 'number',
    },
    ShipCountry: {
      type: 'string',
      enum: [
        'France',
        'Germany',
        'Brazil',
        'Belgium',
        'Switzerland',
        'Venezuela',
        'Austria',
        'Mexico',
        'USA',
        'Sweden',
        'Finland',
        'Spain',
        'UK',
        'Italy',
        'Ireland',
        'Portugal',
        'Canada',
        'Poland',
        'Norway',
        'Denmark',
      ],
    },
  },
  required: ['CustomerID'],
});
